
-- 1
SELECT*FROM cars WHERE cars.id NOT IN (SELECT DISTINCT cars_id FROM customer_cars);
-- 2
CREATE VIEW 


-- !
CREATE VIEW qa AS SELECT*FROM cars WHERE cars.id NOT IN (SELECT DISTINCT cars_id FROM customer_cars);
-- !
CREATE PROCEDURE
-- !
CREATE FUNCTION
-- !
CREATE TRIGGER
-- !
PREPARE sdsf FROM SELECT ......
-- ! TRANSACTION
START TRANSACTION;

COMMIT;

START TRANSACTION;

ROLLBACK;